### ISSUE TITLE
Selective field insert

### ISSUE THREAD

**Issue by yangsir8888** [dongbin86/flink-clickhouse-sink#1]
If you want to select the field insert, you can't use it. For example, my three fields, name age sex, I just want to insert name sex. How can I do this？I'm looking forward to your reply,Thank you.

**Comment by dongbin86** [comment]
Well, currently only full column sequential writes are supported, and if you need to specify a field, it's easy to implement, and you if you want to change the code, welcome PR

**Comment by yangsir8888** [comment]
> Well, currently only full column sequential writes are supported, and if you need to specify a field, it's easy to implement, and you if you want to change the code, welcome PR

OK, thank you. I have a field in the Clickhouse that specifies the datetime type. There is such an exception when writing in sequence. Does HTTP writing not support this operation? Exception: cannot parse string '2020-12-28 16:21:00' as date: syntax error at position 10 (parsed just '2020-12-28 16:21:00'): while executing 'function todate (_ dummy_ 0) Date = toDate(_ dummy_ 0)

**Comment by dongbin86** [comment]
@1763734039 
```
(
    `timestamp` DateTime('Europe/Moscow'),
    `event_id` UInt8
)
ENGINE = TinyLog;

```

`INSERT INTO dt Values (1546300800, 1), ('2019-01-01 00:00:00', 2);`


try timestamp

**Comment by yangsir8888** [comment]
> @1763734039
> 
> ```
> (
>     `timestamp` DateTime('Europe/Moscow'),
>     `event_id` UInt8
> )
> ENGINE = TinyLog;
> ```
> 
> `INSERT INTO dt Values (1546300800, 1), ('2019-01-01 00:00:00', 2);`
> 
> try timestamp

OK, thank you very much. I found the problem. I'll test whether the data will be lost after the task is restarted or the program is abnormal.
